import type { WgslModule } from '@virtual-planet/compiler';

import { MATH_ABS_MODULE } from './math/abs.js';
import { MATH_ADD_MODULE } from './math/add.js';
import { MATH_SUBTRACT_MODULE } from './math/subtract.js';
import { MATH_DIVIDE_MODULE } from './math/divide.js';
import { MATH_MIN_MODULE } from './math/min.js';
import { MATH_NEGATE_MODULE } from './math/negate.js';
import { MATH_MAX_MODULE } from './math/max.js';
import { MATH_BIAS_MODULE } from './math/bias.js';
import { MATH_CLAMP_MODULE } from './math/clamp.js';
import { MATH_GAIN_MODULE } from './math/gain.js';
import { MATH_MIX_MODULE } from './math/mix.js';
import { MATH_MULTIPLY_MODULE } from './math/multiply.js';
import { MATH_POW_MODULE } from './math/pow.js';
import { MATH_REMAP_MODULE } from './math/remap.js';
import { MATH_SMOOTHSTEP_MODULE } from './math/smoothstep.js';
import { NOISE_FBM_MODULE } from './noise/fbm.js';
import {
	NOISE_BLUE2D_MODULE,
	NOISE_HASH2D_MODULE,
	NOISE_PERLIN2D_DERIV_MODULE,
	NOISE_PERLIN2D_MODULE,
	NOISE_VALUE2D_MODULE,
	NOISE_VORONOI2D_MODULE,
	NOISE_WORLEY2D_MODULE
} from './noise/harvest2d.js';
import { NOISE_PERLIN3D_MODULE } from './noise/perlin3d.js';
import { NOISE_RIDGED_FBM_MODULE } from './noise/ridgedFbm.js';
import { NOISE_SIMPLEX_MODULE } from './noise/simplex.js';
import { NOISE_WORLEY_MODULE } from './noise/worley.js';
import { PROCEDURAL_METRIC_POSITION_MODULE } from './procedural/metricPosition.js';
import { PROCEDURAL_UV_MODULE } from './procedural/uv.js';
import { EFFECT_COSINE_PALETTE_MODULE } from './effect/index.js';
import {
	HOST_FRAG_COORD_MODULE,
	HOST_IRESOLUTION_MODULE,
	HOST_ITIME_MODULE
} from './host/index.js';
import { SURFACE_CUBE_SPHERE_MODULE } from './surface/cubeSphere.js';
import { SURFACE_PLANE_MODULE } from './surface/plane.js';
import {
	COLOR_HSV_TO_RGB_MODULE,
	COLOR_LINEAR_TO_SRGB_MODULE,
	COLOR_SRGB_TO_LINEAR_MODULE
} from './color/index.js';
import {
	SDF_BOX_MODULE,
	SDF_CIRCLE_MODULE,
	SDF_OP_INTERSECT_MODULE,
	SDF_OP_SUBTRACT_MODULE,
	SDF_OP_UNION_MODULE,
	SDF_SEGMENT_MODULE
} from './sdf/index.js';
import {
	MATERIAL_PBR_LIGHTING_MODULE,
	SURFACE_CUBE_FACE_DIR_MODULE,
	TERRAIN_BIOME_MATERIAL_MODULE,
	TERRAIN_DETAIL_FBM_MODULE,
	TERRAIN_DOMAIN_WARP_MODULE,
	TERRAIN_FINE_TEXTURE_NOISE_MODULE,
	TERRAIN_HEIGHT_REMAP_MODULE,
	TERRAIN_NORMAL_ESTIMATOR_MODULE,
	TERRAIN_POLAR_TERM_MODULE,
	TERRAIN_SELF_SHADOW_MODULE,
	TERRAIN_VORONOI_MODULE,
	TERRAIN_WORLD_NORMAL_MODULE
} from './terrain/index.js';

function copyModule(mod: {
	id: string;
	source: string;
	dependencies?: readonly string[];
}): WgslModule {
	if (mod.dependencies) {
		return { id: mod.id, source: mod.source, dependencies: [...mod.dependencies] };
	}
	return { id: mod.id, source: mod.source };
}

/** Stable module id → WGSL source for the procedural standard library. */
export const STANDARD_LIBRARY_MODULES: Record<string, WgslModule> = {
	[PROCEDURAL_UV_MODULE.id]: copyModule(PROCEDURAL_UV_MODULE),
	[PROCEDURAL_METRIC_POSITION_MODULE.id]: copyModule(PROCEDURAL_METRIC_POSITION_MODULE),
	[HOST_FRAG_COORD_MODULE.id]: copyModule(HOST_FRAG_COORD_MODULE),
	[HOST_IRESOLUTION_MODULE.id]: copyModule(HOST_IRESOLUTION_MODULE),
	[HOST_ITIME_MODULE.id]: copyModule(HOST_ITIME_MODULE),
	[EFFECT_COSINE_PALETTE_MODULE.id]: copyModule(EFFECT_COSINE_PALETTE_MODULE),
	[NOISE_PERLIN3D_MODULE.id]: copyModule(NOISE_PERLIN3D_MODULE),
	[NOISE_HASH2D_MODULE.id]: copyModule(NOISE_HASH2D_MODULE),
	[NOISE_VALUE2D_MODULE.id]: copyModule(NOISE_VALUE2D_MODULE),
	[NOISE_PERLIN2D_MODULE.id]: copyModule(NOISE_PERLIN2D_MODULE),
	[NOISE_PERLIN2D_DERIV_MODULE.id]: copyModule(NOISE_PERLIN2D_DERIV_MODULE),
	[NOISE_WORLEY2D_MODULE.id]: copyModule(NOISE_WORLEY2D_MODULE),
	[NOISE_VORONOI2D_MODULE.id]: copyModule(NOISE_VORONOI2D_MODULE),
	[NOISE_BLUE2D_MODULE.id]: copyModule(NOISE_BLUE2D_MODULE),
	[NOISE_SIMPLEX_MODULE.id]: copyModule(NOISE_SIMPLEX_MODULE),
	[NOISE_WORLEY_MODULE.id]: copyModule(NOISE_WORLEY_MODULE),
	[NOISE_FBM_MODULE.id]: copyModule(NOISE_FBM_MODULE),
	[NOISE_RIDGED_FBM_MODULE.id]: copyModule(NOISE_RIDGED_FBM_MODULE),
	[COLOR_SRGB_TO_LINEAR_MODULE.id]: copyModule(COLOR_SRGB_TO_LINEAR_MODULE),
	[COLOR_LINEAR_TO_SRGB_MODULE.id]: copyModule(COLOR_LINEAR_TO_SRGB_MODULE),
	[COLOR_HSV_TO_RGB_MODULE.id]: copyModule(COLOR_HSV_TO_RGB_MODULE),
	[SDF_CIRCLE_MODULE.id]: copyModule(SDF_CIRCLE_MODULE),
	[SDF_BOX_MODULE.id]: copyModule(SDF_BOX_MODULE),
	[SDF_SEGMENT_MODULE.id]: copyModule(SDF_SEGMENT_MODULE),
	[SDF_OP_UNION_MODULE.id]: copyModule(SDF_OP_UNION_MODULE),
	[SDF_OP_SUBTRACT_MODULE.id]: copyModule(SDF_OP_SUBTRACT_MODULE),
	[SDF_OP_INTERSECT_MODULE.id]: copyModule(SDF_OP_INTERSECT_MODULE),
	[MATH_REMAP_MODULE.id]: copyModule(MATH_REMAP_MODULE),
	[MATH_CLAMP_MODULE.id]: copyModule(MATH_CLAMP_MODULE),
	[MATH_SMOOTHSTEP_MODULE.id]: copyModule(MATH_SMOOTHSTEP_MODULE),
	[MATH_ADD_MODULE.id]: copyModule(MATH_ADD_MODULE),
	[MATH_SUBTRACT_MODULE.id]: copyModule(MATH_SUBTRACT_MODULE),
	[MATH_DIVIDE_MODULE.id]: copyModule(MATH_DIVIDE_MODULE),
	[MATH_MIN_MODULE.id]: copyModule(MATH_MIN_MODULE),
	[MATH_MAX_MODULE.id]: copyModule(MATH_MAX_MODULE),
	[MATH_NEGATE_MODULE.id]: copyModule(MATH_NEGATE_MODULE),
	[MATH_MULTIPLY_MODULE.id]: copyModule(MATH_MULTIPLY_MODULE),
	[MATH_MIX_MODULE.id]: copyModule(MATH_MIX_MODULE),
	[MATH_POW_MODULE.id]: copyModule(MATH_POW_MODULE),
	[MATH_ABS_MODULE.id]: copyModule(MATH_ABS_MODULE),
	[MATH_BIAS_MODULE.id]: copyModule(MATH_BIAS_MODULE),
	[MATH_GAIN_MODULE.id]: copyModule(MATH_GAIN_MODULE),
	[SURFACE_PLANE_MODULE.id]: copyModule(SURFACE_PLANE_MODULE),
	[SURFACE_CUBE_SPHERE_MODULE.id]: copyModule(SURFACE_CUBE_SPHERE_MODULE),
	[TERRAIN_DOMAIN_WARP_MODULE.id]: copyModule(TERRAIN_DOMAIN_WARP_MODULE),
	[TERRAIN_VORONOI_MODULE.id]: copyModule(TERRAIN_VORONOI_MODULE),
	[TERRAIN_DETAIL_FBM_MODULE.id]: copyModule(TERRAIN_DETAIL_FBM_MODULE),
	[TERRAIN_HEIGHT_REMAP_MODULE.id]: copyModule(TERRAIN_HEIGHT_REMAP_MODULE),
	[TERRAIN_FINE_TEXTURE_NOISE_MODULE.id]: copyModule(TERRAIN_FINE_TEXTURE_NOISE_MODULE),
	[TERRAIN_POLAR_TERM_MODULE.id]: copyModule(TERRAIN_POLAR_TERM_MODULE),
	[TERRAIN_BIOME_MATERIAL_MODULE.id]: copyModule(TERRAIN_BIOME_MATERIAL_MODULE),
	[TERRAIN_NORMAL_ESTIMATOR_MODULE.id]: copyModule(TERRAIN_NORMAL_ESTIMATOR_MODULE),
	[TERRAIN_WORLD_NORMAL_MODULE.id]: copyModule(TERRAIN_WORLD_NORMAL_MODULE),
	[TERRAIN_SELF_SHADOW_MODULE.id]: copyModule(TERRAIN_SELF_SHADOW_MODULE),
	[MATERIAL_PBR_LIGHTING_MODULE.id]: copyModule(MATERIAL_PBR_LIGHTING_MODULE),
	[SURFACE_CUBE_FACE_DIR_MODULE.id]: copyModule(SURFACE_CUBE_FACE_DIR_MODULE)
};

export {
	MATH_ABS_MODULE,
	MATH_ADD_MODULE,
	MATH_BIAS_MODULE,
	MATH_CLAMP_MODULE,
	MATH_GAIN_MODULE,
	MATH_MIX_MODULE,
	MATH_MULTIPLY_MODULE,
	MATH_POW_MODULE,
	MATH_REMAP_MODULE,
	MATH_SMOOTHSTEP_MODULE,
	NOISE_FBM_MODULE,
	NOISE_HASH2D_MODULE,
	NOISE_VALUE2D_MODULE,
	NOISE_PERLIN2D_MODULE,
	NOISE_PERLIN2D_DERIV_MODULE,
	NOISE_WORLEY2D_MODULE,
	NOISE_VORONOI2D_MODULE,
	NOISE_BLUE2D_MODULE,
	NOISE_PERLIN3D_MODULE,
	NOISE_RIDGED_FBM_MODULE,
	NOISE_SIMPLEX_MODULE,
	NOISE_WORLEY_MODULE,
	PROCEDURAL_METRIC_POSITION_MODULE,
	PROCEDURAL_UV_MODULE,
	EFFECT_COSINE_PALETTE_MODULE,
	HOST_FRAG_COORD_MODULE,
	HOST_IRESOLUTION_MODULE,
	HOST_ITIME_MODULE,
	COLOR_HSV_TO_RGB_MODULE,
	COLOR_LINEAR_TO_SRGB_MODULE,
	COLOR_SRGB_TO_LINEAR_MODULE,
	SDF_BOX_MODULE,
	SDF_CIRCLE_MODULE,
	SDF_OP_INTERSECT_MODULE,
	SDF_OP_SUBTRACT_MODULE,
	SDF_OP_UNION_MODULE,
	SDF_SEGMENT_MODULE,
	SURFACE_CUBE_SPHERE_MODULE,
	SURFACE_PLANE_MODULE,
	TERRAIN_BIOME_MATERIAL_MODULE,
	TERRAIN_DETAIL_FBM_MODULE,
	TERRAIN_DOMAIN_WARP_MODULE,
	TERRAIN_FINE_TEXTURE_NOISE_MODULE,
	TERRAIN_HEIGHT_REMAP_MODULE,
	TERRAIN_NORMAL_ESTIMATOR_MODULE,
	TERRAIN_POLAR_TERM_MODULE,
	TERRAIN_SELF_SHADOW_MODULE,
	TERRAIN_VORONOI_MODULE,
	TERRAIN_WORLD_NORMAL_MODULE,
	MATERIAL_PBR_LIGHTING_MODULE,
	SURFACE_CUBE_FACE_DIR_MODULE
};

export { MATH_ABS_SOURCE } from './math/abs.js';
export { MATH_ADD_SOURCE } from './math/add.js';
export { MATH_BIAS_SOURCE } from './math/bias.js';
export { MATH_CLAMP_SOURCE } from './math/clamp.js';
export { MATH_GAIN_SOURCE } from './math/gain.js';
export { MATH_MIX_SOURCE } from './math/mix.js';
export { MATH_MULTIPLY_SOURCE } from './math/multiply.js';
export { MATH_POW_SOURCE } from './math/pow.js';
export { MATH_REMAP_SOURCE } from './math/remap.js';
export { MATH_SMOOTHSTEP_SOURCE } from './math/smoothstep.js';
export { NOISE_FBM_SOURCE } from './noise/fbm.js';
export {
	NOISE_BLUE2D_SOURCE,
	NOISE_HASH2D_SOURCE,
	NOISE_PERLIN2D_DERIV_SOURCE,
	NOISE_PERLIN2D_SOURCE,
	NOISE_VALUE2D_SOURCE,
	NOISE_VORONOI2D_SOURCE,
	NOISE_WORLEY2D_SOURCE
} from './noise/harvest2d.js';
export { NOISE_IGN_MODULE, NOISE_IGN_SOURCE } from './noise/ign.js';
export { NOISE_PERLIN3D_SOURCE } from './noise/perlin3d.js';
export { NOISE_RIDGED_FBM_SOURCE } from './noise/ridgedFbm.js';
export { NOISE_SIMPLEX_SOURCE } from './noise/simplex.js';
export { NOISE_WORLEY_SOURCE } from './noise/worley.js';
export { PROCEDURAL_METRIC_POSITION_SOURCE } from './procedural/metricPosition.js';
export { PROCEDURAL_UV_SOURCE } from './procedural/uv.js';
export {
	EFFECT_COSINE_PALETTE_SOURCE
} from './effect/index.js';
export {
	HOST_FRAG_COORD_SOURCE,
	HOST_IRESOLUTION_SOURCE,
	HOST_ITIME_SOURCE
} from './host/index.js';
export { SURFACE_CUBE_SPHERE_SOURCE } from './surface/cubeSphere.js';
export { SURFACE_PLANE_SOURCE } from './surface/plane.js';
export {
	COLOR_HSV_TO_RGB_SOURCE,
	COLOR_LINEAR_TO_SRGB_SOURCE,
	COLOR_SRGB_TO_LINEAR_SOURCE
} from './color/index.js';
export {
	SDF_BOX_SOURCE,
	SDF_CIRCLE_SOURCE,
	SDF_OP_INTERSECT_SOURCE,
	SDF_OP_SUBTRACT_SOURCE,
	SDF_OP_UNION_SOURCE,
	SDF_SEGMENT_SOURCE
} from './sdf/index.js';
export {
	MATERIAL_PBR_LIGHTING_SOURCE,
	SURFACE_CUBE_FACE_DIR_SOURCE,
	TERRAIN_BIOME_MATERIAL_SOURCE,
	TERRAIN_DETAIL_FBM_SOURCE,
	TERRAIN_DOMAIN_WARP_SOURCE,
	TERRAIN_FINE_TEXTURE_NOISE_SOURCE,
	TERRAIN_HEIGHT_REMAP_SOURCE,
	TERRAIN_NORMAL_ESTIMATOR_SOURCE,
	TERRAIN_POLAR_TERM_SOURCE,
	TERRAIN_SELF_SHADOW_SOURCE,
	TERRAIN_VORONOI_SOURCE,
	TERRAIN_WORLD_NORMAL_SOURCE
} from './terrain/index.js';
