import type { WgslModule } from '@world-lab/compiler';

import { MATH_ABS_MODULE } from './math/abs.js';
import { MATH_ADD_MODULE } from './math/add.js';
import { MATH_SUBTRACT_MODULE } from './math/subtract.js';
import { MATH_DIVIDE_MODULE } from './math/divide.js';
import { MATH_MIN_MODULE } from './math/min.js';
import { MATH_NEGATE_MODULE } from './math/negate.js';
import { MATH_MAX_MODULE } from './math/max.js';
import { MATH_BIAS_MODULE } from './math/bias.js';
import { MATH_CLAMP_MODULE } from './math/clamp.js';
import { MATH_GAIN_MODULE } from './math/gain.js';
import { MATH_MIX_MODULE } from './math/mix.js';
import { MATH_MULTIPLY_MODULE } from './math/multiply.js';
import { MATH_POW_MODULE } from './math/pow.js';
import { MATH_REMAP_MODULE } from './math/remap.js';
import { MATH_NORMALIZE_MODULE } from './math/normalize.js';
import { MATH_SMOOTHSTEP_MODULE } from './math/smoothstep.js';
import { NOISE_FBM_MODULE } from './noise/fbm.js';
import {
	NOISE_BLUE2D_MODULE,
	NOISE_HASH2D_MODULE,
	NOISE_PERLIN2D_DERIV_MODULE,
	NOISE_PERLIN2D_MODULE,
	NOISE_VALUE2D_MODULE,
	NOISE_VORONOI2D_MODULE,
	NOISE_WORLEY2D_MODULE
} from './noise/harvest2d.js';
import { NOISE_PERLIN3D_MODULE } from './noise/perlin3d.js';
import { NOISE_RIDGED_FBM_MODULE } from './noise/ridgedFbm.js';
import { NOISE_SIMPLEX_MODULE } from './noise/simplex.js';
import { NOISE_WORLEY_MODULE } from './noise/worley.js';
import { EFFECT_COSINE_PALETTE_MODULE } from './effect/index.js';
import { SURFACE_CUBE_FACE_MODULE } from './surface/cubeFace.js';
import { SURFACE_CUBE_SPHERE_MODULE } from './surface/cubeSphere.js';
import { SURFACE_PLANE_MODULE } from './surface/plane.js';
import {
	COLOR_COLORLAB_COMMON_MODULE,
	COLOR_HSV_TO_RGB_MODULE,
	COLOR_LAB_TO_XYZ_MODULE,
	COLOR_LINEAR_TO_SRGB_MODULE,
	COLOR_LSRGB_TO_OKLAB_MODULE,
	COLOR_LUV_TO_XYZ_MODULE,
	COLOR_OKLAB_TO_LSRGB_MODULE,
	COLOR_OKLAB_TO_OKLCH_MODULE,
	COLOR_OKLCH_TO_OKLAB_MODULE,
	COLOR_SRGB_TO_LINEAR_MODULE,
	COLOR_SRGB_TO_XYZ_MODULE,
	COLOR_SRGB_TRANSFER_INV_MODULE,
	COLOR_SRGB_TRANSFER_MODULE,
	COLOR_XYZ_TO_LAB_MODULE,
	COLOR_XYZ_TO_LUV_MODULE,
	COLOR_XYZ_TO_SRGB_MODULE,
	COLOR_CHROMATIC_ADAPT_MODULE
} from './color/index.js';
import {
	SDF_BOX_MODULE,
	SDF_CIRCLE_MODULE,
	SDF_OP_INTERSECT_MODULE,
	SDF_OP_SUBTRACT_MODULE,
	SDF_OP_UNION_MODULE,
	SDF_SEGMENT_MODULE
} from './sdf/index.js';
import {
	MATERIAL_PBR_LIGHTING_MODULE,
	SURFACE_CUBE_FACE_DIR_MODULE,
	TERRAIN_BIOME_MATERIAL_MODULE,
	TERRAIN_DETAIL_FBM_MODULE,
	TERRAIN_DOMAIN_WARP_MODULE,
	TERRAIN_FINE_TEXTURE_NOISE_MODULE,
	TERRAIN_HEIGHT_REMAP_MODULE,
	TERRAIN_NORMAL_ESTIMATOR_MODULE,
	TERRAIN_POLAR_TERM_MODULE,
	TERRAIN_SELF_SHADOW_MODULE,
	TERRAIN_VORONOI_MODULE,
	TERRAIN_WORLD_NORMAL_MODULE
} from './terrain/index.js';
import {
	GEOMETRY_PLANE_MODULE,
	STAGE_VERTEX_MODULE
} from './pipeline/stubs.js';
import {
	TRANSFORM_NORMAL_DISPLACE_MODULE,
	TRANSFORM_ROTATE_MODULE,
	TRANSFORM_SCALE_MODULE,
	TRANSFORM_SPHERIFY_MODULE,
	TRANSFORM_TRANSLATE_MODULE
} from './transform/index.js';
import {
	CONSTANT_F32_MODULE,
	VECTOR_VEC2F_MODULE,
	VECTOR_VEC2F_X_MODULE,
	VECTOR_VEC2F_Y_MODULE,
	VECTOR_VEC3F_MODULE,
	VECTOR_VEC3F_X_MODULE,
	VECTOR_VEC3F_Y_MODULE,
	VECTOR_VEC3F_Z_MODULE,
	VECTOR_VEC4F_MODULE,
	VECTOR_VEC4F_W_MODULE,
	VECTOR_VEC4F_X_MODULE,
	VECTOR_VEC4F_Y_MODULE,
	VECTOR_VEC4F_Z_MODULE,
	VECTOR_MATH_MODULES,
	VECTOR_COMBINE_MODULES
} from './vector/index.js';

function copyModule(mod: {
	id: string;
	source: string;
	dependencies?: readonly string[];
}): WgslModule {
	if (mod.dependencies) {
		return { id: mod.id, source: mod.source, dependencies: [...mod.dependencies] };
	}
	return { id: mod.id, source: mod.source };
}

/** Stable module id → WGSL source for the procedural standard library. */
export const STANDARD_LIBRARY_MODULES: Record<string, WgslModule> = {
	[EFFECT_COSINE_PALETTE_MODULE.id]: copyModule(EFFECT_COSINE_PALETTE_MODULE),
	[NOISE_PERLIN3D_MODULE.id]: copyModule(NOISE_PERLIN3D_MODULE),
	[NOISE_HASH2D_MODULE.id]: copyModule(NOISE_HASH2D_MODULE),
	[NOISE_VALUE2D_MODULE.id]: copyModule(NOISE_VALUE2D_MODULE),
	[NOISE_PERLIN2D_MODULE.id]: copyModule(NOISE_PERLIN2D_MODULE),
	[NOISE_PERLIN2D_DERIV_MODULE.id]: copyModule(NOISE_PERLIN2D_DERIV_MODULE),
	[NOISE_WORLEY2D_MODULE.id]: copyModule(NOISE_WORLEY2D_MODULE),
	[NOISE_VORONOI2D_MODULE.id]: copyModule(NOISE_VORONOI2D_MODULE),
	[NOISE_BLUE2D_MODULE.id]: copyModule(NOISE_BLUE2D_MODULE),
	[NOISE_SIMPLEX_MODULE.id]: copyModule(NOISE_SIMPLEX_MODULE),
	[NOISE_WORLEY_MODULE.id]: copyModule(NOISE_WORLEY_MODULE),
	[NOISE_FBM_MODULE.id]: copyModule(NOISE_FBM_MODULE),
	[NOISE_RIDGED_FBM_MODULE.id]: copyModule(NOISE_RIDGED_FBM_MODULE),
	[COLOR_SRGB_TO_LINEAR_MODULE.id]: copyModule(COLOR_SRGB_TO_LINEAR_MODULE),
	[COLOR_LINEAR_TO_SRGB_MODULE.id]: copyModule(COLOR_LINEAR_TO_SRGB_MODULE),
	[COLOR_HSV_TO_RGB_MODULE.id]: copyModule(COLOR_HSV_TO_RGB_MODULE),
	[COLOR_COLORLAB_COMMON_MODULE.id]: copyModule(COLOR_COLORLAB_COMMON_MODULE),
	[COLOR_SRGB_TRANSFER_MODULE.id]: copyModule(COLOR_SRGB_TRANSFER_MODULE),
	[COLOR_SRGB_TRANSFER_INV_MODULE.id]: copyModule(COLOR_SRGB_TRANSFER_INV_MODULE),
	[COLOR_SRGB_TO_XYZ_MODULE.id]: copyModule(COLOR_SRGB_TO_XYZ_MODULE),
	[COLOR_XYZ_TO_SRGB_MODULE.id]: copyModule(COLOR_XYZ_TO_SRGB_MODULE),
	[COLOR_XYZ_TO_LAB_MODULE.id]: copyModule(COLOR_XYZ_TO_LAB_MODULE),
	[COLOR_LAB_TO_XYZ_MODULE.id]: copyModule(COLOR_LAB_TO_XYZ_MODULE),
	[COLOR_XYZ_TO_LUV_MODULE.id]: copyModule(COLOR_XYZ_TO_LUV_MODULE),
	[COLOR_LUV_TO_XYZ_MODULE.id]: copyModule(COLOR_LUV_TO_XYZ_MODULE),
	[COLOR_LSRGB_TO_OKLAB_MODULE.id]: copyModule(COLOR_LSRGB_TO_OKLAB_MODULE),
	[COLOR_OKLAB_TO_LSRGB_MODULE.id]: copyModule(COLOR_OKLAB_TO_LSRGB_MODULE),
	[COLOR_OKLAB_TO_OKLCH_MODULE.id]: copyModule(COLOR_OKLAB_TO_OKLCH_MODULE),
	[COLOR_OKLCH_TO_OKLAB_MODULE.id]: copyModule(COLOR_OKLCH_TO_OKLAB_MODULE),
	[COLOR_CHROMATIC_ADAPT_MODULE.id]: copyModule(COLOR_CHROMATIC_ADAPT_MODULE),
	[SDF_CIRCLE_MODULE.id]: copyModule(SDF_CIRCLE_MODULE),
	[SDF_BOX_MODULE.id]: copyModule(SDF_BOX_MODULE),
	[SDF_SEGMENT_MODULE.id]: copyModule(SDF_SEGMENT_MODULE),
	[SDF_OP_UNION_MODULE.id]: copyModule(SDF_OP_UNION_MODULE),
	[SDF_OP_SUBTRACT_MODULE.id]: copyModule(SDF_OP_SUBTRACT_MODULE),
	[SDF_OP_INTERSECT_MODULE.id]: copyModule(SDF_OP_INTERSECT_MODULE),
	[MATH_REMAP_MODULE.id]: copyModule(MATH_REMAP_MODULE),
	[MATH_NORMALIZE_MODULE.id]: copyModule(MATH_NORMALIZE_MODULE),
	[MATH_CLAMP_MODULE.id]: copyModule(MATH_CLAMP_MODULE),
	[MATH_SMOOTHSTEP_MODULE.id]: copyModule(MATH_SMOOTHSTEP_MODULE),
	[MATH_ADD_MODULE.id]: copyModule(MATH_ADD_MODULE),
	[MATH_SUBTRACT_MODULE.id]: copyModule(MATH_SUBTRACT_MODULE),
	[MATH_DIVIDE_MODULE.id]: copyModule(MATH_DIVIDE_MODULE),
	[MATH_MIN_MODULE.id]: copyModule(MATH_MIN_MODULE),
	[MATH_MAX_MODULE.id]: copyModule(MATH_MAX_MODULE),
	[MATH_NEGATE_MODULE.id]: copyModule(MATH_NEGATE_MODULE),
	[MATH_MULTIPLY_MODULE.id]: copyModule(MATH_MULTIPLY_MODULE),
	[MATH_MIX_MODULE.id]: copyModule(MATH_MIX_MODULE),
	[MATH_POW_MODULE.id]: copyModule(MATH_POW_MODULE),
	[MATH_ABS_MODULE.id]: copyModule(MATH_ABS_MODULE),
	[MATH_BIAS_MODULE.id]: copyModule(MATH_BIAS_MODULE),
	[MATH_GAIN_MODULE.id]: copyModule(MATH_GAIN_MODULE),
	[SURFACE_PLANE_MODULE.id]: copyModule(SURFACE_PLANE_MODULE),
	[SURFACE_CUBE_FACE_MODULE.id]: copyModule(SURFACE_CUBE_FACE_MODULE),
	[SURFACE_CUBE_SPHERE_MODULE.id]: copyModule(SURFACE_CUBE_SPHERE_MODULE),
	[TERRAIN_DOMAIN_WARP_MODULE.id]: copyModule(TERRAIN_DOMAIN_WARP_MODULE),
	[TERRAIN_VORONOI_MODULE.id]: copyModule(TERRAIN_VORONOI_MODULE),
	[TERRAIN_DETAIL_FBM_MODULE.id]: copyModule(TERRAIN_DETAIL_FBM_MODULE),
	[TERRAIN_HEIGHT_REMAP_MODULE.id]: copyModule(TERRAIN_HEIGHT_REMAP_MODULE),
	[TERRAIN_FINE_TEXTURE_NOISE_MODULE.id]: copyModule(TERRAIN_FINE_TEXTURE_NOISE_MODULE),
	[TERRAIN_POLAR_TERM_MODULE.id]: copyModule(TERRAIN_POLAR_TERM_MODULE),
	[TERRAIN_BIOME_MATERIAL_MODULE.id]: copyModule(TERRAIN_BIOME_MATERIAL_MODULE),
	[TERRAIN_NORMAL_ESTIMATOR_MODULE.id]: copyModule(TERRAIN_NORMAL_ESTIMATOR_MODULE),
	[TERRAIN_WORLD_NORMAL_MODULE.id]: copyModule(TERRAIN_WORLD_NORMAL_MODULE),
	[TERRAIN_SELF_SHADOW_MODULE.id]: copyModule(TERRAIN_SELF_SHADOW_MODULE),
	[MATERIAL_PBR_LIGHTING_MODULE.id]: copyModule(MATERIAL_PBR_LIGHTING_MODULE),
	[SURFACE_CUBE_FACE_DIR_MODULE.id]: copyModule(SURFACE_CUBE_FACE_DIR_MODULE),
	[GEOMETRY_PLANE_MODULE.id]: copyModule(GEOMETRY_PLANE_MODULE),
	[STAGE_VERTEX_MODULE.id]: copyModule(STAGE_VERTEX_MODULE),
	[TRANSFORM_NORMAL_DISPLACE_MODULE.id]: copyModule(TRANSFORM_NORMAL_DISPLACE_MODULE),
	[TRANSFORM_ROTATE_MODULE.id]: copyModule(TRANSFORM_ROTATE_MODULE),
	[TRANSFORM_SCALE_MODULE.id]: copyModule(TRANSFORM_SCALE_MODULE),
	[TRANSFORM_SPHERIFY_MODULE.id]: copyModule(TRANSFORM_SPHERIFY_MODULE),
	[TRANSFORM_TRANSLATE_MODULE.id]: copyModule(TRANSFORM_TRANSLATE_MODULE),
	[CONSTANT_F32_MODULE.id]: copyModule(CONSTANT_F32_MODULE),
	[VECTOR_VEC2F_MODULE.id]: copyModule(VECTOR_VEC2F_MODULE),
	[VECTOR_VEC3F_MODULE.id]: copyModule(VECTOR_VEC3F_MODULE),
	[VECTOR_VEC4F_MODULE.id]: copyModule(VECTOR_VEC4F_MODULE),
	[VECTOR_VEC2F_X_MODULE.id]: copyModule(VECTOR_VEC2F_X_MODULE),
	[VECTOR_VEC2F_Y_MODULE.id]: copyModule(VECTOR_VEC2F_Y_MODULE),
	[VECTOR_VEC3F_X_MODULE.id]: copyModule(VECTOR_VEC3F_X_MODULE),
	[VECTOR_VEC3F_Y_MODULE.id]: copyModule(VECTOR_VEC3F_Y_MODULE),
	[VECTOR_VEC3F_Z_MODULE.id]: copyModule(VECTOR_VEC3F_Z_MODULE),
	[VECTOR_VEC4F_X_MODULE.id]: copyModule(VECTOR_VEC4F_X_MODULE),
	[VECTOR_VEC4F_Y_MODULE.id]: copyModule(VECTOR_VEC4F_Y_MODULE),
	[VECTOR_VEC4F_Z_MODULE.id]: copyModule(VECTOR_VEC4F_Z_MODULE),
	[VECTOR_VEC4F_W_MODULE.id]: copyModule(VECTOR_VEC4F_W_MODULE),
	...Object.fromEntries(VECTOR_MATH_MODULES.map((mod) => [mod.id, copyModule(mod)])),
	...Object.fromEntries(VECTOR_COMBINE_MODULES.map((mod) => [mod.id, copyModule(mod)]))
};

export {
	MATH_ABS_MODULE,
	MATH_ADD_MODULE,
	MATH_BIAS_MODULE,
	MATH_CLAMP_MODULE,
	MATH_GAIN_MODULE,
	MATH_MIX_MODULE,
	MATH_MULTIPLY_MODULE,
	MATH_POW_MODULE,
	MATH_REMAP_MODULE,
	MATH_NORMALIZE_MODULE,
	MATH_SMOOTHSTEP_MODULE,
	NOISE_FBM_MODULE,
	NOISE_HASH2D_MODULE,
	NOISE_VALUE2D_MODULE,
	NOISE_PERLIN2D_MODULE,
	NOISE_PERLIN2D_DERIV_MODULE,
	NOISE_WORLEY2D_MODULE,
	NOISE_VORONOI2D_MODULE,
	NOISE_BLUE2D_MODULE,
	NOISE_PERLIN3D_MODULE,
	NOISE_RIDGED_FBM_MODULE,
	NOISE_SIMPLEX_MODULE,
	NOISE_WORLEY_MODULE,
	EFFECT_COSINE_PALETTE_MODULE,
	COLOR_HSV_TO_RGB_MODULE,
	COLOR_LINEAR_TO_SRGB_MODULE,
	COLOR_SRGB_TO_LINEAR_MODULE,
	COLOR_COLORLAB_COMMON_MODULE,
	COLOR_SRGB_TRANSFER_MODULE,
	COLOR_SRGB_TRANSFER_INV_MODULE,
	COLOR_SRGB_TO_XYZ_MODULE,
	COLOR_XYZ_TO_SRGB_MODULE,
	COLOR_XYZ_TO_LAB_MODULE,
	COLOR_LAB_TO_XYZ_MODULE,
	COLOR_XYZ_TO_LUV_MODULE,
	COLOR_LUV_TO_XYZ_MODULE,
	COLOR_LSRGB_TO_OKLAB_MODULE,
	COLOR_OKLAB_TO_LSRGB_MODULE,
	COLOR_OKLAB_TO_OKLCH_MODULE,
	COLOR_OKLCH_TO_OKLAB_MODULE,
	COLOR_CHROMATIC_ADAPT_MODULE,
	SDF_BOX_MODULE,
	SDF_CIRCLE_MODULE,
	SDF_OP_INTERSECT_MODULE,
	SDF_OP_SUBTRACT_MODULE,
	SDF_OP_UNION_MODULE,
	SDF_SEGMENT_MODULE,
	SURFACE_CUBE_FACE_MODULE,
	SURFACE_CUBE_SPHERE_MODULE,
	SURFACE_PLANE_MODULE,
	TERRAIN_BIOME_MATERIAL_MODULE,
	TERRAIN_DETAIL_FBM_MODULE,
	TERRAIN_DOMAIN_WARP_MODULE,
	TERRAIN_FINE_TEXTURE_NOISE_MODULE,
	TERRAIN_HEIGHT_REMAP_MODULE,
	TERRAIN_NORMAL_ESTIMATOR_MODULE,
	TERRAIN_POLAR_TERM_MODULE,
	TERRAIN_SELF_SHADOW_MODULE,
	TERRAIN_VORONOI_MODULE,
	TERRAIN_WORLD_NORMAL_MODULE,
	MATERIAL_PBR_LIGHTING_MODULE,
	SURFACE_CUBE_FACE_DIR_MODULE,
	GEOMETRY_PLANE_MODULE,
	STAGE_VERTEX_MODULE,
	TRANSFORM_NORMAL_DISPLACE_MODULE,
	TRANSFORM_ROTATE_MODULE,
	TRANSFORM_SCALE_MODULE,
	TRANSFORM_SPHERIFY_MODULE,
	TRANSFORM_TRANSLATE_MODULE,
	CONSTANT_F32_MODULE,
	VECTOR_VEC2F_MODULE,
	VECTOR_VEC2F_X_MODULE,
	VECTOR_VEC2F_Y_MODULE,
	VECTOR_VEC3F_MODULE,
	VECTOR_VEC3F_X_MODULE,
	VECTOR_VEC3F_Y_MODULE,
	VECTOR_VEC3F_Z_MODULE,
	VECTOR_VEC4F_MODULE,
	VECTOR_VEC4F_W_MODULE,
	VECTOR_VEC4F_X_MODULE,
	VECTOR_VEC4F_Y_MODULE,
	VECTOR_VEC4F_Z_MODULE,
	VECTOR_MATH_MODULES,
	VECTOR_COMBINE_MODULES
};

export { MATH_ABS_SOURCE } from './math/abs.js';
export { MATH_ADD_SOURCE } from './math/add.js';
export { MATH_BIAS_SOURCE } from './math/bias.js';
export { MATH_CLAMP_SOURCE } from './math/clamp.js';
export { MATH_GAIN_SOURCE } from './math/gain.js';
export { MATH_MIX_SOURCE } from './math/mix.js';
export { MATH_MULTIPLY_SOURCE } from './math/multiply.js';
export { MATH_POW_SOURCE } from './math/pow.js';
export { MATH_REMAP_SOURCE } from './math/remap.js';
export { MATH_NORMALIZE_SOURCE } from './math/normalize.js';
export { MATH_SMOOTHSTEP_SOURCE } from './math/smoothstep.js';
export { NOISE_FBM_SOURCE } from './noise/fbm.js';
export {
	NOISE_BLUE2D_SOURCE,
	NOISE_HASH2D_SOURCE,
	NOISE_PERLIN2D_DERIV_SOURCE,
	NOISE_PERLIN2D_SOURCE,
	NOISE_VALUE2D_SOURCE,
	NOISE_VORONOI2D_SOURCE,
	NOISE_WORLEY2D_SOURCE
} from './noise/harvest2d.js';
export { NOISE_IGN_MODULE, NOISE_IGN_SOURCE } from './noise/ign.js';
export { NOISE_PERLIN3D_SOURCE } from './noise/perlin3d.js';
export { NOISE_RIDGED_FBM_SOURCE } from './noise/ridgedFbm.js';
export { NOISE_SIMPLEX_SOURCE } from './noise/simplex.js';
export { NOISE_WORLEY_SOURCE } from './noise/worley.js';
export {
	EFFECT_COSINE_PALETTE_SOURCE
} from './effect/index.js';
export { SURFACE_CUBE_FACE_SOURCE } from './surface/cubeFace.js';
export { SURFACE_CUBE_SPHERE_SOURCE } from './surface/cubeSphere.js';
export { SURFACE_PLANE_SOURCE } from './surface/plane.js';
export {
	COLOR_COLORLAB_COMMON_SOURCE,
	COLOR_HSV_TO_RGB_SOURCE,
	COLOR_LAB_TO_XYZ_SOURCE,
	COLOR_LINEAR_TO_SRGB_SOURCE,
	COLOR_LSRGB_TO_OKLAB_SOURCE,
	COLOR_LUV_TO_XYZ_SOURCE,
	COLOR_OKLAB_TO_LSRGB_SOURCE,
	COLOR_OKLAB_TO_OKLCH_SOURCE,
	COLOR_OKLCH_TO_OKLAB_SOURCE,
	COLOR_SRGB_TO_LINEAR_SOURCE,
	COLOR_SRGB_TO_XYZ_SOURCE,
	COLOR_SRGB_TRANSFER_INV_SOURCE,
	COLOR_SRGB_TRANSFER_SOURCE,
	COLOR_XYZ_TO_LAB_SOURCE,
	COLOR_XYZ_TO_LUV_SOURCE,
	COLOR_XYZ_TO_SRGB_SOURCE,
	COLOR_CHROMATIC_ADAPT_SOURCE
} from './color/index.js';
export {
	SDF_BOX_SOURCE,
	SDF_CIRCLE_SOURCE,
	SDF_OP_INTERSECT_SOURCE,
	SDF_OP_SUBTRACT_SOURCE,
	SDF_OP_UNION_SOURCE,
	SDF_SEGMENT_SOURCE
} from './sdf/index.js';
export {
	MATERIAL_PBR_LIGHTING_SOURCE,
	SURFACE_CUBE_FACE_DIR_SOURCE,
	TERRAIN_BIOME_MATERIAL_SOURCE,
	TERRAIN_DETAIL_FBM_SOURCE,
	TERRAIN_DOMAIN_WARP_SOURCE,
	TERRAIN_FINE_TEXTURE_NOISE_SOURCE,
	TERRAIN_HEIGHT_REMAP_SOURCE,
	TERRAIN_NORMAL_ESTIMATOR_SOURCE,
	TERRAIN_POLAR_TERM_SOURCE,
	TERRAIN_SELF_SHADOW_SOURCE,
	TERRAIN_VORONOI_SOURCE,
	TERRAIN_WORLD_NORMAL_SOURCE
} from './terrain/index.js';
export {
	GEOMETRY_PLANE_SOURCE,
	STAGE_VERTEX_SOURCE
} from './pipeline/stubs.js';
export {
	CONSTANT_F32_SOURCE,
	VECTOR_VEC2F_SOURCE,
	VECTOR_VEC2F_X_SOURCE,
	VECTOR_VEC2F_Y_SOURCE,
	VECTOR_VEC3F_SOURCE,
	VECTOR_VEC3F_X_SOURCE,
	VECTOR_VEC3F_Y_SOURCE,
	VECTOR_VEC3F_Z_SOURCE,
	VECTOR_VEC4F_SOURCE,
	VECTOR_VEC4F_W_SOURCE,
	VECTOR_VEC4F_X_SOURCE,
	VECTOR_VEC4F_Y_SOURCE,
	VECTOR_VEC4F_Z_SOURCE,
	VECTOR_COMBINE_VEC2F_F32_SOURCE,
	VECTOR_COMBINE_VEC3F_F32_SOURCE,
	VECTOR_COMBINE_VEC2F_F32_F32_SOURCE,
	VECTOR_COMBINE_VEC2F_VEC2F_SOURCE
} from './vector/index.js';
